name: PHPStan

on:
  push:
    branches: [ main , ci_cd ]
  pull_request:
    branches: [ main , ci_cd ]



jobs:
  phpstan:
    name: phpstan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./sistem-akademik
    steps:
      - uses: actions/checkout@v2
      - name: List All Source Code
        run: ls -l

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
        
      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Run cp .env.example .env
        run: cp .env.example .env

      - name: Run artisan key:generate
        run: php artisan key:generate

      - name: Run PHPStan
        run: ./vendor/bin/phpstan --error-format=github

      - name: Run Unit Test
        run: ./vendor/bin/phpunit